steps:
  # build the container image
  # - name: 'gcr.io/cloud-builders/docker'
  # args: ['build', '-t', 'gcr.io/$PROJECT_ID/grobel-com', './client']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/grobel-com-server', './server']

  # push the container image to Container Registry
  # - name: 'gcr.io/cloud-builders/docker'
  # args: ['push', 'gcr.io/$PROJECT_ID/grobel-com']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grobel-com-server']

  # Deploy container image to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     [
  #       'beta',
  #       'run',
  #       'deploy',
  #       'grobel-com',
  #       '--image',
  #       'gcr.io/$PROJECT_ID/grobel-com',
  #       '--region',
  #       'us-central1',
  #       '--platform',
  #       'managed',
  #       '--quiet',
  #       '--allow-unauthenticated',
  #     ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'grobel-com-server',
        '--image',
        'gcr.io/$PROJECT_ID/grobel-com-server',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
        '--allow-unauthenticated',
      ]

images:
  # - gcr.io/$PROJECT_ID/grobel-com
  - gcr.io/$PROJECT_ID/grobel-com-server
